version: "3.4"

networks:
  postgres:

volumes:
  postgres-data:

services:
  db:
    image: postgres
    networks:
      - postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adminer:
    image: adminer
    networks:
      - postgres
    ports:
      - 3001:8080
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/usr/src/app/src
      - ./target:/usr/src/app/target
    networks:
      - postgres
    ports:
      - 3000:3000
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
