apiVersion: v1
kind: Service
metadata:
  name: apibeanz-svc
  namespace: apibeanz
  labels:
    app: apibeanz
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: apibeanz
