apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: apibeanz-scaler
  namespace: apibeanz
  labels:
    app: apibeanz
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apibeanz-deploy
  minReplicas: 2
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
