server:
  port: ${PORT}

spring:
  application:
    name: beanz
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${POSTGRES_URL}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

security:
  token:
    secret: ${JWT_TOKEN_SECRET}

finnhub:
  token: ${FINNHUB_API_TOKEN}

logging:
  level:
    org:
      springframework:
        security: error

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}