name: Destroy infra

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform destroy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      # TODO: purge DB

      - name: terraform init
        run: terraform init
        working-directory: ./deploy/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}

      - name: terraform destroy
        run: terraform destroy -auto-approve -input=false
        working-directory: ./deploy/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          TF_VAR_RDB_PASS: ${{ secrets.DB_PASS }}
