name: Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify Integration Tests
        run: mvn -B clean verify -Pintegration-test
        env:
          FINNHUB_API_TOKEN: ${{ secrets.FINNHUB_API_TOKEN }}
